name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build: 

    steps: 
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: npm run create-dockerfile
